In [1]:
import pandas as pd

In [2]:
tran_1 = pd.read_csv(r'C:\MULTICAM_11\csv\tran_1.csv')
tran_2 = pd.read_csv(r'C:\MULTICAM_11\csv\tran_2.csv')

In [3]:
tran_1.head(1)

  transaction_id   price         payment_date customer_id
0    T0000000113  210000  2019-02-01 01:36:57    PL563502

In [4]:
tran_2.head(1)

  transaction_id   price         payment_date customer_id
0    T0000005113  295000  2019-06-15 07:20:27    TS169261

In [5]:
tran_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  5000 non-null   object
 1   price           5000 non-null   int64
 2   payment_date    5000 non-null   object
 3   customer_id     5000 non-null   object
dtypes: int64(1), object(3)
memory usage: 156.4+ KB

In [6]:
tran_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1786 entries, 0 to 1785
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  1786 non-null   object
 1   price           1786 non-null   int64
 2   payment_date    1786 non-null   object
 3   customer_id     1786 non-null   object
dtypes: int64(1), object(3)
memory usage: 55.9+ KB

In [7]:
# tran_1, tran_2 데이터를 결합
    # 두 개의 데이터 프레임은 테이블의 구조가 같은 형태
    # 단순한 행 결합
    # 두 개의 데이터프레임이 행 결합을 하면 rows의 개수는? 5000 + 1786 = 6786
# concat() 함수 이용
# pandas 안에 concat 함수 호출 --> 원본의 데이터라는 개념이 존재 x -> 결과를 저장하려면 새로운 변수에 대입
tran = pd.concat(
    [tran_1, tran_2], axis = 0, ignore_index = True
)

In [8]:
tran.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6786 entries, 0 to 6785
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  6786 non-null   object
 1   price           6786 non-null   int64
 2   payment_date    6786 non-null   object
 3   customer_id     6786 non-null   object
dtypes: int64(1), object(3)
memory usage: 212.2+ KB

In [9]:
tran_d_1 = pd.read_csv(r'C:\MULTICAM_11\csv\tran_d_1.csv')
tran_d_2 = pd.read_csv(r'C:\MULTICAM_11\csv\tran_d_2.csv')

In [10]:
tran_d_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       5000 non-null   int64
 1   transaction_id  5000 non-null   object
 2   item_id         5000 non-null   object
 3   quantity        5000 non-null   int64
dtypes: int64(2), object(2)
memory usage: 156.4+ KB

In [11]:
tran_d_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2144 entries, 0 to 2143
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       2144 non-null   int64
 1   transaction_id  2144 non-null   object
 2   item_id         2144 non-null   object
 3   quantity        2144 non-null   int64
dtypes: int64(2), object(2)
memory usage: 67.1+ KB

In [13]:
# tran_d_1, tran_d_2 데이터 프레임을 단순 행 결합
tran_d = pd.concat(
    [tran_d_1, tran_d_2], axis = 0, ignore_index = True
)

In [14]:
tran_d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7144 entries, 0 to 7143
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       7144 non-null   int64
 1   transaction_id  7144 non-null   object
 2   item_id         7144 non-null   object
 3   quantity        7144 non-null   int64
dtypes: int64(2), object(2)
memory usage: 223.4+ KB

In [15]:
tran.head(1)

  transaction_id   price         payment_date customer_id
0    T0000000113  210000  2019-02-01 01:36:57    PL563502

In [16]:
tran_d.head(1)

   detail_id transaction_id item_id  quantity
0          0    T0000000113    S005         1

In [17]:
# tran과 tran_d 데이터 프레임을 결합
# 테이블의 구조는 다르게 구성 -> 단순한 행 결합은 불가능
# 인덱스의 개수가 다르다 -> 6786 // 7144개의 데이터
# 두 개의 데이터 프레임이 공통적으로 가지고 있는 데이터 컬럼은 존재하는가?
    # transaction_id 컬럼은 공통적으로 가지고 있다. -> 조인결합이 가능
# tran의 인덱스의 수는 6786개
# tran_d의 인덱스의 수는 7144개
    # 두 개의 데이터 프레임을 조인 결합 했을 때 => 인덱스의 수는 어떻게 나올것인가?
    # 6786 // 7144 --> how에 따라 다르게 나올것인가?
transaction = pd.merge(
    tran, tran_d,
    # 조건 (두개의 데이터 프레임이 공통적으로 가지고 있는 컬럼의 이름)
    on = 'transaction_id',
    # 결합의 방식은 어떻게 할 것인가?
    how = 'outer'
)

In [18]:
transaction

,transaction_id,price,payment_date,customer_id,detail_id,item_id,quantity
0,T0000000113,210000,2019-02-01 01:36:57,PL563502,0,S005,1
1,T0000000114,50000,2019-02-01 01:37:23,HD678019,1,S001,1
2,T0000000115,120000,2019-02-01 02:34:19,HD298120,2,S003,1
3,T0000000116,210000,2019-02-01 02:47:23,IK452215,3,S005,1
4,T0000000117,170000,2019-02-01 04:33:46,PL542865,4,S002,2
...,...,...,...,...,...,...,...
7139,T0000006894,180000,2019-07-31 21:20:44,HI400734,7139,S004,1
7140,T0000006895,85000,2019-07-31 21:52:48,AS339451,7140,S002,1
7141,T0000006896,100000,2019-07-31 23:35:25,OA027325,7141,S001,2
7142,T0000006897,85000,2019-07-31 23:39:35,TS624738,7142,S002,1
7143,T0000006898,85000,2019-07-31 23:41:38,AS834214,7143,S002,1

In [19]:
tran_d['transaction_id'].value_counts()

transaction_id
T0000000790    4
T0000000999    3
T0000000397    3
T0000000383    3
T0000000683    3
              ..
T0000006894    1
T0000006895    1
T0000006896    1
T0000006897    1
T0000006898    1
Name: count, Length: 6786, dtype: int64

In [23]:
tran['transaction_id'].describe()

count            6786
unique           6786
top       T0000006898
freq                1
Name: transaction_id, dtype: object

#### 데이터 결합 연습
1.  transaction 데이터프레임과 csv 폴더 안에 item_master 파일을 로드하여 2개의
데이터 프레임을 결합
2. 결합된 데이터에 csv 폴더에 customer_master 파일을 로드하여 데이터 프레임을 결합
3. payment_date 컬럼의 데이터를 시계열 데이터로 변화

In [20]:
item_master = pd.read_csv(r'C:\MULTICAM_11\csv\item_master.csv')

In [21]:
item_master

  item_id item_name  item_price
0    S001      PC-A       50000
1    S002      PC-B       85000
2    S003      PC-C      120000
3    S004      PC-D      180000
4    S005      PC-E      210000

In [22]:
test_1 = pd.merge(
    transaction, item_master,
    on = 'item_id',
    how = 'inner'
)

In [23]:
test_1

,transaction_id,price,payment_date,customer_id,detail_id,item_id,quantity,item_name,item_price
0,T0000000113,210000,2019-02-01 01:36:57,PL563502,0,S005,1,PC-E,210000
1,T0000000114,50000,2019-02-01 01:37:23,HD678019,1,S001,1,PC-A,50000
2,T0000000115,120000,2019-02-01 02:34:19,HD298120,2,S003,1,PC-C,120000
3,T0000000116,210000,2019-02-01 02:47:23,IK452215,3,S005,1,PC-E,210000
4,T0000000117,170000,2019-02-01 04:33:46,PL542865,4,S002,2,PC-B,85000
...,...,...,...,...,...,...,...,...,...
7139,T0000006894,180000,2019-07-31 21:20:44,HI400734,7139,S004,1,PC-D,180000
7140,T0000006895,85000,2019-07-31 21:52:48,AS339451,7140,S002,1,PC-B,85000
7141,T0000006896,100000,2019-07-31 23:35:25,OA027325,7141,S001,2,PC-A,50000
7142,T0000006897,85000,2019-07-31 23:39:35,TS624738,7142,S002,1,PC-B,85000
7143,T0000006898,85000,2019-07-31 23:41:38,AS834214,7143,S002,1,PC-B,85000

In [24]:
customer_master = pd.read_csv(r'C:\MULTICAM_11\csv\customer_master.csv')

In [25]:
customer_master.head(1)

,customer_id,name,class,gender,start_date,end_date,campaign_id,is_deleted
0,OA832399,XXXX,C01,F,2015-05-01 00:00:00,NaN,CA1,0

In [26]:
test_2 = pd.merge(
    test_1, customer_master,
    on = 'customer_id',
    how = 'inner'
)

In [28]:
# 시계열 데이터 payment_date를 컬럼을 타입을 변경
# 문자를 시계열로 변경 (datetime.strptime() // to_datetime())
pd.to_datetime(test_2['payment_date'])

0      2019-02-01 01:36:57
1      2019-02-01 01:37:23
2      2019-02-01 02:34:19
3      2019-02-01 02:47:23
4      2019-02-01 04:33:46
               ...
6064   2019-07-31 20:28:20
6065   2019-07-31 21:17:39
6066   2019-07-31 21:52:48
6067   2019-07-31 23:35:25
6068   2019-07-31 23:41:38
Name: payment_date, Length: 6069, dtype: datetime64[ns]

In [29]:
# datetime 라이브러리의 strptime()을 이용하여 데이터 타입 변환
from datetime import datetime

In [30]:
# datetime 안에 strptime() 함수는 pandas에 to_datetime()과는 다르게 스리즈 형태 변환 불가능
# datetime.strptime(test_1['payment_date'][0], '%Y-%m-%d %H:%M:%S')
# 스리즈 데이터에서 value들을 하나씩 뽑아서 함수에 넣는다.
test_1['payment_date'].map(
    # x에 대입이 되는 데이터는 문자
    lambda x : datetime.strptime(x, '%Y-%m-%d %H:%M:%S')
)

0      2019-02-01 01:36:57
1      2019-02-01 01:37:23
2      2019-02-01 02:34:19
3      2019-02-01 02:47:23
4      2019-02-01 04:33:46
               ...
7139   2019-07-31 21:20:44
7140   2019-07-31 21:52:48
7141   2019-07-31 23:35:25
7142   2019-07-31 23:39:35
7143   2019-07-31 23:41:38
Name: payment_date, Length: 7144, dtype: datetime64[ns]

In [31]:
test_2['payment_date'] = pd.to_datetime(test_2['payment_date'])

In [32]:
test_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6069 entries, 0 to 6068
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  6069 non-null   object
 1   price           6069 non-null   int64
 2   payment_date    6069 non-null   datetime64[ns]
 3   customer_id     6069 non-null   object
 4   detail_id       6069 non-null   int64
 5   item_id         6069 non-null   object
 6   quantity        6069 non-null   int64
 7   item_name       6069 non-null   object
 8   item_price      6069 non-null   int64
 9   name            6069 non-null   object
 10  class           6069 non-null   object
 11  gender          6069 non-null   object
 12  start_date      6069 non-null   object
 13  end_date        1978 non-null   object
 14  campaign_id     6069 non-null   object
 15  is_deleted      6069 non-null   int64
dtypes: datetime64[ns](1), int64(5), object(10)
memory usage: 758.8+ KB

In [33]:
# 요일별 판매가 된 제품들의 총 판매 개수 합계가 어떻게 되는가?
# 요일이라는 새로운 변수를 생성 -> 시계열에서 요일만 따로 추출 (strftime(%A|%a|%w))
test_2['요일'] = test_2['payment_date'].dt.strftime('%A')

In [34]:
test_2['payment_date'].dt.weekday

0       4
1       4
2       4
3       4
4       4
       ..
6064    2
6065    2
6066    2
6067    2
6068    2
Name: payment_date, Length: 6069, dtype: int32

In [35]:
test_2.head(1)

,transaction_id,price,payment_date,customer_id,detail_id,item_id,quantity,item_name,item_price,name,class,gender,start_date,end_date,campaign_id,is_deleted,요일
0,T0000000113,210000,2019-02-01 01:36:57,PL563502,0,S005,1,PC-E,210000,XX,C01,M,2018-07-01 00:00:00,NaN,CA1,0,Friday

In [36]:
# 요일, item_id를 기준으로 그룹화 -> quantity의 합산
test_2[['요일', 'item_id', 'quantity']].groupby(['요일', 'item_id']).sum()

                   quantity
요일        item_id
Friday    S001          406
          S002          250
          S003          140
          S004          105
          S005          225
Monday    S001          363
          S002          201
          S003          132
          S004           97
          S005          207
Saturday  S001          367
          S002          182
          S003          141
          S004          102
          S005          231
Sunday    S001          390
          S002          236
          S003          121
          S004          121
          S005          210
Thursday  S001          334
          S002          206
          S003          128
          S004          103
          S005          227
Tuesday   S001          336
          S002          227
          S003          121
          S004          107
          S005          212
Wednesday S001          382
          S002          216
          S003           98
          S004          122
          S005          241